### PR TITLE
Finished bonus HTML client

### PR DESCRIPTION
**Pull request by a698570**
I've made a static HTML5 file that leverages the browser websockets API to connect with the server.

See: https://github.com/a698570/lab4-websockets/blob/bonus/src/main/html/index.html

### CODE REVIEW

**Comment by fjlopez** [comment]
The HTML file must be served by the Tyrus server as static content (see how in https://github.com/eclipse-ee4j/tyrus/issues/233).

In addition, please, fix:

https://github.com/a698570/lab4-websockets/blob/fbe64d8b2c442489fc6b4b46d9a0e5cde52a53f5/src/main/html/index.html#L31

to avoid hardcoded localhost and ports:

```js
function url(s) {
    var l = window.location;
    return ((l.protocol === "https:") ? "wss://" : "ws://") + l.hostname + (((l.port != 80) && (l.port != 443)) ? ":" + l.port : "") + l.pathname + s;
}
```

**Comment by a698570** [comment]
> The HTML file must be served by the Tyrus server as static content (see how in [eclipse-ee4j/tyrus#233](https://github.com/eclipse-ee4j/tyrus/issues/233)).
> 
> In addition, please, fix:
> 
> https://github.com/a698570/lab4-websockets/blob/fbe64d8b2c442489fc6b4b46d9a0e5cde52a53f5/src/main/html/index.html#L31
> 
> to avoid hardcoded localhost and ports:
> 
> ```js
> function url(s) {
>     var l = window.location;
>     return ((l.protocol === "https:") ? "wss://" : "ws://") + l.hostname + (((l.port != 80) && (l.port != 443)) ? ":" + l.port : "") + l.pathname + s;
> }
> ```

Done: https://github.com/a698570/lab4-websockets/commit/aeb3344653a4af93538b3086a59847769d02852b

**Comment by fjlopez** [comment]
Added a comment  to your commit  https://github.com/a698570/lab4-websockets/commit/aeb3344653a4af93538b3086a59847769d02852b#r36240858

Follow conventions (it is related to where you have put the html file in your directory layout)

**Comment by a698570** [comment]
Fixed: https://github.com/a698570/lab4-websockets/commit/e101603054d94b5d4cff23e5b76a04c4f27894e7

**Pull request merged**
