### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fntkg**

### CODE REVIEW

**Comment by fjlopez** [comment]
Warn me when the solution is on the test branch.

**Comment by fntkg** [comment]
I forgot to commit the changes xd

Now the solution is on the test branch @fjlopez

**Comment by fjlopez** [comment]
Only half of it xD, check again. 

https://github.com/fntkg/lab4-websockets/blob/933997135fa01f89e568aacfcbcbd83a59cb80f8/src/test/kotlin/websockets/ElizaServerTest.kt#L75-L77

**Comment by fntkg** [comment]
the third time lucky

Now it should be completed, i've checked everything again

**Comment by fjlopez** [comment]
Nope:
- line 54 may fail if your laptop is fast (use an assertTrue)
- line 55 may fail because you feel angry and your test tests for weirdness.

**Comment by fntkg** [comment]
Fixed

**Pull request merged**
