### PR TITLE
Primary goal

### PR DESCRIPTION
**Pull request by 780454-unizar**

### CODE REVIEW

**Comment by fjlopez** [comment]
Not yet finished. Report me when it is ready!

**Comment by 780454-unizar** [comment]
It is finished now.

**Comment by fjlopez** [comment]
Not yet. Test fails:
- Line 49, consider a different test as the list size may be either 4 o 5 depending on the CPU load.
- Line 55, when you send "always" none of the selected answers of lines 50-54 is returned by Eliza. Check Eliza code for a better pair of request/answers.

**Comment by fjlopez** [comment]
Please fix ASAP.

**Comment by 780454-unizar** [comment]
It is fixed now. Sorry, I could not do it before.

**Comment by fjlopez** [comment]
... but do the changes  in the code in the other branch, please.  This PR must contain only your changes to README.md!

**Comment by 780454-unizar** [comment]
I think it is correct now.

**Comment by fjlopez** [comment]
**PR accepted**

**Pull request merged**
