### PR TITLE
Primary goal modified

### PR DESCRIPTION
**Pull request by fnonay**

### CODE REVIEW

**Comment by fjlopez** [comment]
Your code don't compile. Please, do a `./gradlew check` before uploading code to GitHub.

**Comment by fjlopez** [comment]
It is not necessary to close the PR. Just fix your test branch and push it, next, warn me here.

**Comment by fnonay** [comment]
Ok Sorry Javi, I didn't know.
I've not seen the character ")" at line 52 in my code. Besides, I've been checking my code executing ./gradlew without parameter "check" and the result was "Build Successful". It's the reason why I was trying to push my changes.

I think the bug is fixed now.

Many thanks,
Felipe

**Comment by fjlopez** [comment]
The test is disabled, enable it first:

https://github.com/fnonay/lab4-websockets/blob/test/src/test/kotlin/websockets/ElizaServerTest.kt#L40

In addition, test hangs forever because:

https://github.com/fnonay/lab4-websockets/blob/test/src/test/kotlin/websockets/ElizaServerTest.kt#L71

```kotlin
latch.count.equals(1)
```

will be always `false` because `count` returns a `Long`. It should be:

```kotlin
latch.count.equals(1L)
```
or

```kotlin
latch.count == 1L
```

Next, ensure response agains all possibilities ("no" has two, "Why not?" and "Are you sure?") . 

You can test it using the GitHub `codespace` feature in the test branch.

**Comment by fnonay** [comment]
Hello again Javi, I've changed and revised the bugs.

Sorry for the inconveniences.

Many thanks,
Felipe

**Comment by fjlopez** [comment]
**PR accepted**

**Pull request merged**
