### PR TITLE
Primary goal

### PR DESCRIPTION
**Pull request by arejula27**

### CODE REVIEW

**Comment by arejula27** [comment]
This is the correct one instead of the #23

**Comment by fjlopez** [comment]
It seems that something keeps wrong.

https://github.com/arejula27/lab4-websockets/blob/test/src/test/kotlin/websockets/ElizaServerTest.kt

does not contain you updated tests.

**Comment by arejula27** [comment]
I push the test, i forgot them on my second pc without uploading. My Apologies.

**Comment by arejula27** [comment]
I have just done a small correction. I think it is completed now.

**Comment by fjlopez** [comment]
**PR accepted**

**Pull request merged**
